apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
  namespace: selenium-grid
spec:
  type: NodePort
  selector:
    app: selenium-hub
  ports:
    - name: ui
      port: 4444
      targetPort: 4444
      nodePort: 30007
    - name: event-bus-publish
      port: 4442
      targetPort: 4442
    - name: event-bus-subscribe
      port: 4443
      targetPort: 4443
